// This file will be automatically generated by GitHub Actions
// For local development, it contains sample data
window.NOTES_DATA = {
  "LLM.md": {
    "title": "LLM",
    "content": "# LLM\n\nLarge Language Models tag page.",
    "tags": [],
    "status": "",
    "folder": "3-Tags",
    "links": []
  },
  "未命名.md": {
    "title": "未命名",
    "content": "# 未命名\n\nUntitled note.",
    "tags": [],
    "status": "",
    "folder": "3-Tags",
    "links": []
  },

  "Deep Dive into LLMs like ChatGPT.md": {
    "title": "Deep Dive into LLMs like ChatGPT",
    "content": "2025-08-09      11:06\n\nStatus: #Unfinished\n\nTags: [[LLM]]\n\n\n# Deep Dive into LLMs like ChatGPT\n\n主要观点：\n\n1. 大模型的记忆非常重要，当在大模型的会话框内给出参考的上下文，可以显著提升模型表现\n2. 大模型的数学能力一般较弱，与其让其做算术（相当于人类心算），不如让其生成代码\n3. 大模型和人类思考存在显著差异，分词化的操作也有问题，例如识别一个单词里有几个字母这类简单任务也会出错\n\n\n# References\n\n\n\n\n\n",
    "tags": ["LLM"],
    "status": "Unfinished",
    "folder": "6-Full Notes",
    "links": ["LLM.md"]
  },
  "Smolagents源码学习.md": {
    "title": "Smolagents源码学习",
    "content": "# Smolagents源码学习\n\nSource code analysis of Smolagents.",
    "tags": [],
    "status": "",
    "folder": "6-Full Notes",
    "links": []
  }
};